# Generated by Django 3.2.7 on 2021-09-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='abolfazlj00', max_length=50),
        ),
    ]
