# Generated by Django 3.2.7 on 2021-09-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_pass_token',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
