# Generated by Django 3.2.7 on 2021-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_like_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like_numbers',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
