# Generated by Django 3.2.7 on 2021-09-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_like_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_numbers',
        ),
    ]
