# Generated by Django 3.2.7 on 2021-09-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
