# Generated by Django 3.2.7 on 2021-09-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
