# Generated by Django 3.2.7 on 2021-09-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_code',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
