# Generated by Django 3.2.7 on 2021-10-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_staff_staff_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
    ]
