# Generated by Django 3.2.7 on 2021-10-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_delete_like'),
        ('store', '0022_remove_discount_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
