# Generated by Django 3.2.7 on 2021-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_discount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
