# Generated by Django 3.2.7 on 2021-10-08 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20211008_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.PositiveIntegerField(help_text='per cent', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
