# Generated by Django 3.2.7 on 2021-10-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
