# Generated by Django 3.2.7 on 2021-10-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_liked_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
