# Generated by Django 3.2.7 on 2021-10-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_discount_user'),
        ('customer', '0006_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.discount'),
        ),
    ]
